name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    test:
        permissions:
            id-token: write
            contents: read

        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2

        - name: Run tests
          run: |
            python get.py
    
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3.19
          timeout-minutes: 60
          with:
            limit-access-to-actor: false